#!/bin/sh
SID=$1

if [ -z "$SID" ]; then
  echo "Missing SID parameter"
  exit 1
fi

export ORAENV_ASK=NO 
export ORACLE_SID=$SID
. oraenv 1>/dev/null

DB_STATUS=$(sqlplus -S / as sysdba << EOF
set pages 0 feedback off
select status from v\$instance;
exit
EOF
)

printf "%s" "$DB_STATUS"
