#!/bin/sh

SID=$1

if [ -z "$SID" ]; then
  echo "Missing SID parameter"
  exit 1
fi

DBV=$2

if [ -z "$DBV" ]; then
  echo "Missing DBV parameter"
  exit 1
fi

ERCOLE_HOME=/opt/ERCOLE-agent
if [ ! -d ${ERCOLE_HOME} ]; then
  ERCOLE_HOME=.
fi

export ORAENV_ASK=NO 
export ORACLE_SID=$SID
. oraenv 1>/dev/null

if [ "$DBV" = "12" ]; then
  sqlplus -S "/ AS SYSDBA" < ${ERCOLE_HOME}/sql/patch-12.sql
else
  sqlplus -S "/ AS SYSDBA" < ${ERCOLE_HOME}/sql/patch.sql
fi
